### ISSUE TITLE
Consolidation of Cinnamenu

### ISSUE THREAD

**Issue by erwn16** [fredcw/Cinnamenu.json#3]
Hello,
I would like to contribute to Cinnamenu but I don't know whether my support would fit to your plans. 

From my point of view there is a need to provide some explanations with regard to the use of search providers - especially for less experienced users.
Another aspect is the usage of web bookmarks from Firefox. This feature still doesn't work - may be because of a missing package.

Which work should I do?

Kind regards, erwn16

**Comment by fredcw** [comment]
@erwn16 I don't really like the idea of the search providers because downloading and installing them is too complicated for the average user. If any of the search providers are things that many people would find useful then I think it would be better to implement them in cinnamenu.

Yes the firefox bookmarks don't seem to work. I've tried installing the required package (gir1.2-gda-5.0) in manjaro and mint but they still didn't work. The bookmarks code is a few years old and probably need updating but I don't know how it works or how to fix it. If you could get the firefox bookmarks working, that would be great, although to be fair, I don't know how many people would use this feature but I suspect some people might like it.

**Comment by erwn16** [comment]
@fredcw I made the proposal with regard to the search providers because there is still the button in the settings dialogue which leads to additional examples.

I am a novice in JS and from that point of view my proposal concerned only the test of the required package that you mentioned. Firefox received a major update a few years ago. If the respective code in Cinnamenu is older it has to be adapted to the new concepts of Firefox.

The files in the category "Recent" are probably sorted but the criterion used for the sort is not displayed. So it is difficult to find a file in the list easily. As only the names of the files are displayed an alphabetical order of the filenames would make it easier to find a file. Is it possible to sort the files alphabetically or does Cinnamenu use Recent.js from Cinnamon and thus has no chance to resort the list?

**Comment by fredcw** [comment]
@erwn16 I've decided to remove the options relating to search providers. They'll still work but there'll be no option to turn them off.
The recent files are sorted by the most recently opened. It would be easy to sort them alphabetically but I'm not sure that's a good idea.

You may be right about people wanting to select other categories to open the menu on, it's hard to tell but I haven't had any requests for this option.

I'm not even sure if the web bookmarks are a good idea. I don't see why someone would want search their bookmarks when they can just open a browser tab and see their bookmarks in the order in which they placed them?
